# Generated by Django 5.1.6 on 2025-02-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebanksprices',
            name='possible_range_prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progarantii_app.possiblerangeprices'),
        ),
    ]
