# Generated by Django 5.1.6 on 2025-03-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseBanksPrices',
            new_name='BaseBankPercent',
        ),
        migrations.RenameModel(
            old_name='MinBanksPrices',
            new_name='MinBankPrice',
        ),
    ]
