# Generated by Django 5.1.6 on 2025-03-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0002_alter_basebanksprices_possible_range_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='AKRA_rating',
            field=models.CharField(blank=True, choices=[('AAA(RU)', 'AAA(RU)'), ('AA+(RU)', 'AA+(RU)'), ('AA(RU)', 'AA(RU)'), ('AA-(RU)', 'AA-(RU)'), ('A+(RU)', 'A+(RU)'), ('A+(RU)', 'A+(RU)'), ('A(RU)', 'A(RU)'), ('A-(RU)', 'A-(RU)'), ('BBB+(RU)', 'BBB+(RU)'), ('BBB+(RU)', 'BBB+(RU)'), ('BBB(RU)', 'BBB(RU)'), ('BBB-(RU)', 'BBB-(RU)'), ('BB+(RU)', 'BB+(RU)'), ('BB+(RU)', 'BB+(RU)'), ('BB(RU)', 'BB(RU)'), ('BB-(RU)', 'BB-(RU)'), ('B+(RU)', 'B+(RU)'), ('B(RU)', 'B(RU)'), ('B-(RU)', 'B-(RU)')], max_length=50, verbose_name='Рейтинг АКР'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='Expert_RA',
            field=models.CharField(blank=True, choices=[('ruAAA', 'ruAAA'), ('ruAA+', 'ruAA+'), ('ruAA', 'ruAA'), ('ruAA-', 'ruAA-'), ('ruA+', 'ruA+'), ('ruA', 'ruA'), ('ruA-', 'ruA-'), ('ruBBB+', 'ruBBB+'), ('ruBBB', 'ruBBB'), ('ruBBB-', 'ruBBB-'), ('ruBB+', 'ruBB+'), ('ruBB', 'ruBB'), ('ruBB-', 'ruBB-'), ('ruB+', 'ruB+'), ('ruB', 'ruB'), ('ruB-', 'ruB-')], max_length=50, null=True, verbose_name='Рейтинг Эксперт РА'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='daterangename',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Имя диапазона'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='type_of_guarantee',
            field=models.CharField(blank=True, choices=[('Участие', 'Участие'), ('Исполнение', 'Исполнение'), ('Гарантийные обязательства', 'Гарантийные обязательства')], max_length=50, null=True, verbose_name='Тип гарантии'),
        ),
        migrations.AlterField(
            model_name='law',
            name='type_of_law',
            field=models.CharField(blank=True, choices=[('№ 44', '№ 44'), ('№ 223', '№ 223'), ('№ 615', '№ 615'), ('ком', 'ком')], max_length=50, null=True, verbose_name='Тип закона'),
        ),
        migrations.AlterField(
            model_name='pricerangename',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Имя диапазона'),
        ),
    ]
