# Generated by Django 5.1.6 on 2025-03-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0003_bank_license_number_bank_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterange',
            name='date_range_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_ranges', to='progarantii_app.daterangename', verbose_name='Название диапазона'),
        ),
        migrations.AlterField(
            model_name='law',
            name='type_of_law',
            field=models.CharField(blank=True, choices=[('44', '44'), ('223', '223'), ('615', '615'), ('ком', 'ком')], max_length=50, null=True, verbose_name='Тип закона'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='price_range_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='progarantii_app.pricerangename', verbose_name='Название диапазона'),
        ),
    ]
