# Generated by Django 5.1.6 on 2025-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0004_alter_daterange_date_range_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='type_of_law',
            field=models.CharField(blank=True, choices=[('№ 44', '№ 44'), ('№ 223', '№ 223'), ('№ 615', '№ 615')], max_length=50, null=True, verbose_name='Тип закона'),
        ),
    ]
