# Generated by Django 5.1.6 on 2025-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0005_alter_law_type_of_law'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='type_of_law',
        ),
        migrations.AddField(
            model_name='law',
            name='number_of_law',
            field=models.PositiveIntegerField(blank=True, choices=[(44, 44), (223, 223), (615, 615)], max_length=50, null=True, verbose_name='Номер закона'),
        ),
    ]
