# Generated by Django 5.1.6 on 2025-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0007_alter_law_number_of_law'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='number_of_law',
        ),
        migrations.AddField(
            model_name='law',
            name='type_of_law',
            field=models.CharField(blank=True, choices=[('№ 44', '№ 44'), ('№ 223', '№ 223'), ('№ 615', '№ 615')], max_length=50, null=True, verbose_name='Тип закона'),
        ),
    ]
