# Generated by Django 5.1.6 on 2025-03-13 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progarantii_app', '0008_remove_law_number_of_law_law_type_of_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minbankprice',
            name='min_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Минимальное значение'),
        ),
    ]
